import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/Component/Layout/Navbar";
import Footer from "@/Component/Layout/Footer";
import NextauthProvider from "@/Provider/NextauthProvider";
import Toastprovider from "@/Provider/Toastprovider";



const poppins = Poppins({
  weight: ["100", "200", "400", "500", "600", "800"],
});

export const metadata = {
  title: "TrustCare Connect",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <NextauthProvider>

    <html lang="en">
      <body
        className={`${poppins.className} antialiased`}
      >
        <header>
          <Navbar></Navbar>
        </header>
        <main  className=" bg-gradient-to-br from-[#e0e4e2] to-[#cfd4d0]">

        {children}
        <Toastprovider></Toastprovider>
        </main>
        <Footer></Footer>
      </body>
    </html>
    
    </NextauthProvider>
  );
}
